export const ErrorCodes = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  
  // Marketplace Errors
  MARKETPLACE_INVALID_LISTING: 'MARKETPLACE_INVALID_LISTING',
  MARKETPLACE_INSUFFICIENT_FUNDS: 'MARKETPLACE_INSUFFICIENT_FUNDS',
  MARKETPLACE_LISTING_NOT_FOUND: 'MARKETPLACE_LISTING_NOT_FOUND',
  MARKETPLACE_ORDER_FAILED: 'MARKETPLACE_ORDER_FAILED',
  
  // Wallet Errors
  WALLET_CONNECTION_FAILED: 'WALLET_CONNECTION_FAILED',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  
  // API Errors
  API_RATE_LIMIT_EXCEEDED: 'API_RATE_LIMIT_EXCEEDED',
  API_INVALID_REQUEST: 'API_INVALID_REQUEST',
  API_SERVER_ERROR: 'API_SERVER_ERROR',
  
  // Data Errors
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  DATA_CONFLICT: 'DATA_CONFLICT',
  
  // Network Errors
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED'
} as const;